// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327101747_FinishAddingEmails")]
    partial class FinishAddingEmails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Artist_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset_Num")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Collection_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Donor_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Loan_Status_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Location_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediumId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Medium_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Retail_High_Estimate")
                        .HasColumnType("REAL");

                    b.Property<double?>("Retail_Low_Estimate")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artist_Id");

                    b.HasIndex("Asset_Num")
                        .IsUnique();

                    b.HasIndex("Category_Id");

                    b.HasIndex("Collection_Id");

                    b.HasIndex("Donor_Id");

                    b.HasIndex("Loan_Status_Id");

                    b.HasIndex("Location_Id");

                    b.HasIndex("MediumId");

                    b.ToTable("Artwork");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("backend.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("backend.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Donor");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Artwork_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artwork_Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("backend.Models.Loan_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique();

                    b.ToTable("Loan_Status");
                });

            modelBuilder.Entity("backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Location_Name")
                        .IsUnique();

                    b.ToTable("Location");
                });

            modelBuilder.Entity("backend.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Medium");
                });

            modelBuilder.Entity("backend.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordReset");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Curator"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Facilities"
                        },
                        new
                        {
                            Id = 3,
                            Title = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Guest"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.HasOne("backend.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("Artist_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("Artworks")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Collection", "Collection")
                        .WithMany("Artworks")
                        .HasForeignKey("Collection_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Donor", "Donor")
                        .WithMany("Artworks")
                        .HasForeignKey("Donor_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Loan_Status", "Loan_Status")
                        .WithMany("Artworks")
                        .HasForeignKey("Loan_Status_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Location", "Location")
                        .WithMany("Artworks")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Medium", "Medium")
                        .WithMany("Artworks")
                        .HasForeignKey("MediumId");

                    b.Navigation("Artist");

                    b.Navigation("Category");

                    b.Navigation("Collection");

                    b.Navigation("Donor");

                    b.Navigation("Loan_Status");

                    b.Navigation("Location");

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.HasOne("backend.Models.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("Artwork_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("backend.Models.PasswordReset", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("PasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Collection", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Donor", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Loan_Status", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Location", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Medium", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("PasswordResets");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
