// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Artist_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset_Num")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Collection_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Donor_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Loan_Status_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Location_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediumId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Medium_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Retail_High_Estimate")
                        .HasColumnType("REAL");

                    b.Property<double?>("Retail_Low_Estimate")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artist_Id");

                    b.HasIndex("Asset_Num")
                        .IsUnique();

                    b.HasIndex("Category_Id");

                    b.HasIndex("Collection_Id");

                    b.HasIndex("Donor_Id");

                    b.HasIndex("Loan_Status_Id");

                    b.HasIndex("Location_Id");

                    b.HasIndex("MediumId");

                    b.ToTable("Artwork");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("backend.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("backend.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Donor");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Artwork_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artwork_Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("backend.Models.Loan_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loan_Status");
                });

            modelBuilder.Entity("backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("backend.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medium");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.HasOne("backend.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("Artist_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("Artworks")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Collection", "Collection")
                        .WithMany("Artworks")
                        .HasForeignKey("Collection_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Donor", "Donor")
                        .WithMany("Artworks")
                        .HasForeignKey("Donor_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Loan_Status", "Loan_Status")
                        .WithMany("Artworks")
                        .HasForeignKey("Loan_Status_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Location", "Location")
                        .WithMany("Artworks")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Medium", "Medium")
                        .WithMany("Artworks")
                        .HasForeignKey("MediumId");

                    b.Navigation("Artist");

                    b.Navigation("Category");

                    b.Navigation("Collection");

                    b.Navigation("Donor");

                    b.Navigation("Loan_Status");

                    b.Navigation("Location");

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.HasOne("backend.Models.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("Artwork_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Artwork", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Collection", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Donor", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Loan_Status", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Location", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("backend.Models.Medium", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
